### PR TITLE
upgrade to Vuetify 2

### PR DESCRIPTION
**Pull request by cavatron**
- v2 uses Sass over Stylus, so webpack now uses sass-loader
- moved away from some deprecated attributes and components
- added global Vuetify object to main Vue instance, as seen in Vuetify's Vue CLI 3 plugin
- switched to [new grid system](https://vuetifyjs.com/en/components/grids)

### CODE REVIEW

**Comment by Kocal** [comment]
Well, I've tried to fix conflicts on GitHub but I don't know what happens with `package.json`...
And I still can't fix it myself because I can't push on your fork. :/

**Comment by cavatron** [comment]
Ah, yeah,  it looks like merging master into this branch downgraded Vuetify to 1.x in package.json. I'll get that fixed today. What do you think about rebasing when updating PR branches instead of merging? That way the package.json edits would have been kept

**Comment by cavatron** [comment]
it also appears that this project currently used Node 8, which has been deprecated. v10 is now LTS. I'll see if I can get it to build that way

**Comment by cavatron** [comment]
:tada: Here's [the link](https://5da250c21396970008686074--vuetify-algolia-places.netlify.com/) to the deploy preview. Should be good now to merge, unless you find some other issue

**Comment by cavatron** [comment]
force pushed a commit with the changes for Vuetify 2 because I forgot to merge the changes from upstream into my fork before making new commits to this branch.

I created a mess for myself but cleaned it up :grin: 
It should be okay to merge now

**Comment by Kocal** [comment]
Seems legit to me, thanks! :)

**Comment by Kocal** [comment]
@cavatron friendly ping to notify you that the version 1.0.0 of this package (with vuetify 2 support) has been published :)

**Pull request merged**
